config/routes.rb
Appheradashboard::Application.routes.draw do
  resources :folders

  resources :types

  resources :items

  post 'accounts/payment'
  match 'purchases/new' => "purchases#new"
  match 'purchases/create' => "purchases#create"

  resources :listings
  resources :plans

  resources :subscriptions do
    collection do
      post :change_plan
    end
  end



  resources :contacts

  match 'resellers/setscope' => 'resellers#setscope', :as => :setscope
  match 'page/network' => 'pages#network'
  resources :resellers
  root :to => 'home#index'


  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "omniauth_callbacks",  :passwords => 'passwords'} do
    get '/users/auth/:provider' => 'omniauth_callbacks#twitter'
  end
    get '/home/city_autocomplete'
  resources :home
  resources :users
  resources :reports
  
  # from old dashboard
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sentiments
      resources :keywords
      resources :organizations
      resources :uptime_monitors
    end
  end
  
  # resources :pages do
  #     member { post :mercury_update }
  #   end
 
 # ActiveAdmin.routes(self)
 
 # scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
  #devise_for :admin_users, ActiveAdmin::Devise.config, ActiveAdmin::Devise.config
  
  
  resources :ProxiesApi
  

  resources :start

  resources :reviewers

  resources :accounts do
    collection do
      post :update_credit_card
    end
  end

  resources :rankings

  resources :keywords
  
  resources :misc

 # match 'new_organizations/new' => 'new_organizations/new'
  match 'reviews/test' => 'reviews#index2'
  match 'reviewers2/test' => 'reviewers#index2'
  
  

  resources :reviews

  resources :aggregate_results
  
 # match 'organizations/unlink' => 'organizations#unlink'
  match 'organizations/myorgs' => 'organizations#myorgs'
  match 'organizations/mapview' => 'organizations#mapview'

  resources :organizations do
    collection do
      get :autocomplete_city
      post :autocomplete_categories
    end
  end

  resources :recommendations
  resources :uptime_monitors
  resources :my_competitors

  resources :history_items

  #match 'api/organizations' => 'api#organizations'
 
  # namespace :reseller do
  #     resources :accounts
  #     resources :organizations
  #   end
  
  
  
end

app/models/listing.rb
class Listing < ActiveRecord::Base

  attr_accessible :city, :content_provider, :name, :organization_id, :phone, :street, :zip
  belongs_to :organization


  def self.paginate(options = {})
    page(options[:page]).per(options[:per_page])
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # GET /listings
  # GET /listings.json
  def index
    @listings = @org.listings

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(params[:listing])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render json: @listing, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @listings.each do |listing| %>
  <tr>
    <td><%= listing.name %></td>
    <td><%= listing.street %></td>
    <td><%= listing.zip %></td>
    <td><%= listing.city %></td>
    <td><%= listing.phone %></td>
    <td><%= listing.content_provider %></td>
    <td><%= listing.created_at %></td>




    <td><%= link_to 'Show', listing %></td>
    <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
    <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>