config/routes.rb
Appheradashboard::Application.routes.draw do
  resources :folders

  resources :types

  resources :items

  post 'accounts/payment'
  match 'purchases/new' => "purchases#new"
  match 'purchases/create' => "purchases#create"

  resources :listings
  resources :plans

  resources :subscriptions do
    collection do
      post :change_plan
    end
  end



  resources :contacts

  match 'resellers/setscope' => 'resellers#setscope', :as => :setscope
  match 'page/network' => 'pages#network'
  resources :resellers
  root :to => 'home#index'


  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "omniauth_callbacks",  :passwords => 'passwords'} do
    get '/users/auth/:provider' => 'omniauth_callbacks#twitter'
  end
    get '/home/city_autocomplete'
  resources :home
  resources :users
  resources :reports
  
  # from old dashboard
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sentiments
      resources :keywords
      resources :organizations
      resources :uptime_monitors
    end
  end
  
  # resources :pages do
  #     member { post :mercury_update }
  #   end
 
 # ActiveAdmin.routes(self)
 
 # scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
  #devise_for :admin_users, ActiveAdmin::Devise.config, ActiveAdmin::Devise.config
  
  
  resources :ProxiesApi
  

  resources :start

  resources :reviewers

  resources :accounts do
    collection do
      post :update_credit_card
    end
  end

  resources :rankings

  resources :keywords
  
  resources :misc

 # match 'new_organizations/new' => 'new_organizations/new'
  match 'reviews/test' => 'reviews#index2'
  match 'reviewers2/test' => 'reviewers#index2'
  
  

  resources :reviews

  resources :aggregate_results
  
 # match 'organizations/unlink' => 'organizations#unlink'
  match 'organizations/myorgs' => 'organizations#myorgs'
  match 'organizations/mapview' => 'organizations#mapview'

  resources :organizations do
    collection do
      get :autocomplete_city
      post :autocomplete_categories
    end
  end

  resources :recommendations
  resources :uptime_monitors
  resources :my_competitors

  resources :history_items

  #match 'api/organizations' => 'api#organizations'
 
  # namespace :reseller do
  #     resources :accounts
  #     resources :organizations
  #   end
  
  
  
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/folders_controller.rb
class FoldersController < InheritedResources::Base
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= simple_form_for(@folder) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<h1>Listing folders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @folders.each do |folder| %>
  <tr>
    <td><%= folder.name %></td>
    <td><%= folder.description %></td>
    <td><%= link_to 'Show', folder %></td>
    <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
    <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @folder.name %>
</p>

<p>
  <b>Description:</b>
  <%= @folder.description %>
</p>


<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>