config/routes.rb
Appheradashboard::Application.routes.draw do
  resources :folders

  resources :types

  resources :items

  post 'accounts/payment'
  match 'purchases/new' => "purchases#new"
  match 'purchases/create' => "purchases#create"

  resources :listings
  resources :plans

  resources :subscriptions do
    collection do
      post :change_plan
    end
  end



  resources :contacts

  match 'resellers/setscope' => 'resellers#setscope', :as => :setscope
  match 'page/network' => 'pages#network'
  resources :resellers
  root :to => 'home#index'


  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "omniauth_callbacks",  :passwords => 'passwords'} do
    get '/users/auth/:provider' => 'omniauth_callbacks#twitter'
  end
    get '/home/city_autocomplete'
  resources :home
  resources :users
  resources :reports
  
  # from old dashboard
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sentiments
      resources :keywords
      resources :organizations
      resources :uptime_monitors
    end
  end
  
  # resources :pages do
  #     member { post :mercury_update }
  #   end
 
 # ActiveAdmin.routes(self)
 
 # scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
  #devise_for :admin_users, ActiveAdmin::Devise.config, ActiveAdmin::Devise.config
  
  
  resources :ProxiesApi
  

  resources :start

  resources :reviewers

  resources :accounts do
    collection do
      post :update_credit_card
    end
  end

  resources :rankings

  resources :keywords
  
  resources :misc

 # match 'new_organizations/new' => 'new_organizations/new'
  match 'reviews/test' => 'reviews#index2'
  match 'reviewers2/test' => 'reviewers#index2'
  
  

  resources :reviews

  resources :aggregate_results
  
 # match 'organizations/unlink' => 'organizations#unlink'
  match 'organizations/myorgs' => 'organizations#myorgs'
  match 'organizations/mapview' => 'organizations#mapview'

  resources :organizations do
    collection do
      get :autocomplete_city
      post :autocomplete_categories
    end
  end

  resources :recommendations
  resources :uptime_monitors
  resources :my_competitors

  resources :history_items

  #match 'api/organizations' => 'api#organizations'
 
  # namespace :reseller do
  #     resources :accounts
  #     resources :organizations
  #   end
  
  
  
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :plan
  belongs_to :user
  validates_presence_of :plan_id

  attr_accessible :plan_id, :user_id, :updated_at
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < InheritedResources::Base
  def new

    @user = current_user
    @plan = Plan.all
    @subscription = nil
    if current_user.subscriptions.present?
      @subscription = current_user.subscriptions.order('updated_at desc').first
    end
  end

  def create
    @subscription = Subscription.new(params[:subscription])
    if @subscription.save_with_payment
      redirect_to @subscription, :notice => "Thank you for subscribing!"
    else
      render :new
    end
  end

  def show
    @subscription = Subscription.find(params[:id])
  end

  def change_plan
    if current_user.credit_card.blank? || current_user.account.blank?
      respond_to do |format|
        format.json { render json: {:status => :failure} }
      end
    else
      plan = Plan.find(params["plan_id"])
      sub = current_user.subscriptions
      if sub.blank?
        Subscription.create({:plan_id => params["plan_id"].to_i, :user_id => current_user.id})

        Stripe::Charge.create(
            :amount => plan.price,
            :currency => "usd",
            :customer => current_user.credit_card.stripe_customer_id
        )
      else
        sub_active = sub.where({:plan_id => plan.id}).first
        if (sub_active.blank?)
            Subscription.create({:plan_id => params["plan_id"].to_i, :user_id => current_user.id})
            Stripe::Charge.create(
                :amount => plan.price,
                :currency => "usd",
                :customer => current_user.credit_card.stripe_customer_id
            )
        else
          sub_active.update_attributes({:updated_at => Time.now})
        end

      end
      respond_to do |format|
        format.json { render json: {:status => :ok} }
      end
    end

  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/backup-new.html.erb
<h1>Signing up for "<%= @subscription.plan.name %>"</h1>
<p>Includes <strong><%= @subscription.plan %> Basic Monitorings</strong> for only <strong><%= number_to_currency @subscription.plan.price %></strong> per month!</p>

<%= form_for @subscription do |f| %>
    <% if @subscription.errors.any? %>
        <div class="error_messages">
          <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
          <ul>
            <% @subscription.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :plan_id %>

    <%= f.hidden_field :stripe_card_token %>

    <% if @subscription.stripe_card_token.present? %>
        Credit card has been provided.
    <% else %>
        <div class="field">
          <%= label_tag :card_number, "Credit Card Number" %>
          <%= text_field_tag :card_number, nil, name: nil %>
        </div>
        <div class="field">
          <%= label_tag :card_code, "Security Code on Card (CVV)" %>
          <%= text_field_tag :card_code, nil, name: nil %>
        </div>
        <div class="field">
          <%= label_tag :card_month, "Card Expiration" %>
          <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
          <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
        </div>
    <% end %>
    <div id="stripe_error">
      <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
    </div>
    <div class="actions">
      <%= f.submit "Subscribe" %>
    </div>
<% end %>

app/views/subscriptions/new.html.erb
<%= stylesheet_link_tag "subscriptions", :media => "all" %>

<script type="text/javascript">
    Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
    $(document).ready(function() {
        $('#submit_upgrade').click(function() {
            var form = $(this).closest('form');
            form.validate({
                errorLabelContainer: $('#flash-notice-error'),
                errorElement: "p",
                rules: {
                    'credit_card[card_zip]': {
                        required: true
                    },
                    'credit_card[card_cvc]': {
                        required: true,
                        number: true
                    },
                    'credit_card[month_expiration]': {
                        required: true,
                        number: true
                    },
                    'credit_card[year_expiration]': {
                        required: true,
                        number: true
                    }
                },
                messages: {
                    'credit_card[card_zip]': {
                        required: "field card number is required."
                    },
                    'credit_card[card_cvc]': {
                        required: "field card cvv is required.",
                        number: "field card cvv must be number."
                    },
                    'credit_card[month_expiration]': {
                        required: "field month expiration is required.",
                        number: "month expiration must be number."
                    },
                    'credit_card[year_expiration]': {
                        required: "field year expiration is required.",
                        number: "year expiration must be number."
                    }
                }
            })
            if (form.valid()) {
                $('#flash-notice-error').empty();
                form.append('<img src="/assets/Metro/loading.gif" style="margin-left: 8px"/>');
                form.find('#submit_upgrade').attr('disabled', 'disabled');
                Stripe.createToken({
                    number: form.find('input[name="credit_card[card_zip]"]').val(),
                    cvc: form.find('input[name="credit_card[card_cvc]"]').val(),
                    exp_month: form.find('input[name="credit_card[month_expiration]"]').val(),
                    exp_year: form.find('input[name="credit_card[year_expiration]"]').val()
                }, function(status, response) {
                    if (response.error) {

                    } else {
                        $.ajax({
                            type: "POST",
                            url: "/accounts/update_credit_card",
                            data: {
                                "credit_card[card_zip]": form.find('input[name="credit_card[card_zip]"]').val(),
                                "credit_card[card_cvc]": form.find('input[name="credit_card[card_cvc]"]').val(),
                                "credit_card[month_expiration]": form.find('input[name="credit_card[month_expiration]"]').val(),
                                "credit_card[year_expiration]": form.find('input[name="credit_card[year_expiration]"]').val(),
                                "credit_card[stripe_customer_id]": response.id,
                                "credit_card[card_type]": response.card.type
                            },
                            dataType: "json",
                            beforeSend: function() {
                            },
                            success: function(response) {
                                if (response.status == 'ok') {
                                    form.find('#submit_upgrade').removeAttr('disabled')
                                    $('#flash-notice-success').empty().show().html('<div class="alert alert-success">Upgrading successfully</div>');
                                    $.each($('#list-subscription .btn'), function(value, index) {
                                        if ($(this).attr('class').indexOf('btn-success') == -1)
                                            $(this).removeAttr('disabled')
                                    });

                                }
                                else if (response.status == 'failure') {
                                    $('#flash-notice-error').empty().show().html('<div class="alert alert-error">Having problem when upgrade</div>');
                                }
                                form.children('img').remove()
                            },
                            error: function(response) {
                                $('#flash-notice-error').empty().show().html('<div class="alert alert-error">Having problem when upgrade</div>');
                                form.children('img').remove()
                            }
                        })
                    }
                });
            }
            return false;
        })
        $('.stdtable .btn').click(function() {
            var obj = $(this);
            $.ajax({
                type: "POST",
                url: "/subscriptions/change_plan",
                data: {
                    plan_id: $(this).closest('tr').attr('id').substr(7)
                },
                dataType: "json",
                beforeSend: function() {
                    obj.parent().append('<img src="/assets/Metro/loading.gif" style="margin: 8px 12px; position: absolute;"/>');
                    obj.attr('disabled', 'disabled');
                },
                success: function(response) {
                    obj.parent().children('img').remove();
                    obj.removeAttr('disabled');
                    if (response.status == 'ok') {
                        obj.closest('.stdtable').find('.btn-success').removeClass('btn-success').removeAttr('disabled').text('Active')
                        obj.addClass('btn-success').attr('disabled', 'disabled').text('Deactive')
                    }
                    else if (response.status == 'failure'){
                        $('#flash-notice-error').empty().show().html('<div class="alert alert-error">Having problem when changing plan</div>');
                    }
                },
                error: function(response) {
                    obj.parent().children('img').remove();
                }
            })
        })
    });
</script>

<div id="masthead">

  <div class="container">

    <div class="masthead-pad">

      <div class="masthead-text">
        <h3><span class="translation_missing" title=""><%= t('subscription.title') %></span></h3>
      </div>
      <!-- /.masthead-text -->

    </div>

  </div>
  <!-- /.container -->

</div>

<div id="content">

  <div class="container">


    <div class="row">

      <div class="span12">
        <div id="flash-notice-error" class="alert alert-error hide">

        </div>
        <div id="flash-notice-success">

        </div>
        <div class="hero-unit" style="padding-top: 16px">
          <h2><%= t('subscription.credit_card') %></h2>
          <div data="">
            <%= form_for(current_user.credit_card || CreditCard.new(), :url => '/accounts/payment') do |f| %>
                <div class="form-row">
                  <%= f.label :card_zip, t('subscription.card_zip') %>
                  <%= f.text_field :card_zip %>
                </div>

                <div class="form-row">
                  <%= f.label :card_cvc , t('subscription.card_cvc ')%>
                  <%= f.text_field :card_cvc %>
                </div>

                <div class="form-row">
                  <%= f.label :month_expiration , t('subscription.month_expiration')%>
                  <%= f.text_field :month_expiration %>
                </div>

                <div class="form-row">
                  <%= f.label :year_expiration , t('subscription.year_expiration') %>
                  <%= f.text_field :year_expiration %>
                </div>
                <%= f.submit t('subscription.submit_payment'), :id => "submit_upgrade", :class => "btn"%>
            <% end%>


          </div>
          <a href="/accounts"><%= t('back') %></a>
        </div>
        <div class="hero-unit" style="padding-top: 16px">
          <h2><%= t('subscription.list_subscription') %></h2>
          <% if current_user.account.present? && current_user.account.organizations.present?%>
              <div data="">
                <table class="stdtable width800" id="list-subscription">
                  <thead>
                      <th><%= t('subscription.plan_name') %></th>
                      <th><%= t('subscription.price') %></th>
                      <th><%= t('subscription.status') %></th>
                  </thead>
                  <tbody>

                        <% @plan.each do |plan| %>
                          <tr id="planid-<%= plan.id%>">
                            <% if current_user.credit_card.blank?%>
                                <td><%= t("activerecord.plan." + plan.name)%></td>
                                <td><%= plan.price%> $</td>
                                <td><button class="btn" disabled="disabled"><%= t('subscription.active') %></button></td>
                            <% elsif @subscription.present? && @subscription.plan.id == plan.id%>
                                <td><%= t("activerecord.plan." + plan.name)%></td>
                                <td><%= plan.price%> $</td>
                                <td><button class="btn btn-success" disabled="disabled"><%= t('subscription.deactive') %></button></td>
                            <% else %>
                                <td><%= t("activerecord.plan." + plan.name)%></td>
                                <td><%= plan.price%> $</td>
                                <td><button class="btn"><%=  t('subscription.active') %></button></td>
                            <% end%>
                          </tr>
                        <% end%>
                  </tbody>
                </table>
              </div>
          <% else %>
             <h5><%= t('subscription.no_plan')%></h5>
          <% end%>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('subscription.user') %>:</b>
  <%= @subscription.user_id %>
</p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>